package com.hd.ibus.pojo;

import java.io.Serializable;
import java.util.Date;

public class IbusVi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.va
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double va;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.vb
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double vb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.vc
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double vc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.ia
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double ia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.ib
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double ib;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.ic
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double ic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.ac_time
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Date acTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_vi.node_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.id
     *
     * @return the value of ibus_vi.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.id
     *
     * @param id the value for ibus_vi.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.va
     *
     * @return the value of ibus_vi.va
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getVa() {
        return va;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.va
     *
     * @param va the value for ibus_vi.va
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setVa(Double va) {
        this.va = va;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.vb
     *
     * @return the value of ibus_vi.vb
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getVb() {
        return vb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.vb
     *
     * @param vb the value for ibus_vi.vb
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setVb(Double vb) {
        this.vb = vb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.vc
     *
     * @return the value of ibus_vi.vc
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getVc() {
        return vc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.vc
     *
     * @param vc the value for ibus_vi.vc
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setVc(Double vc) {
        this.vc = vc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.ia
     *
     * @return the value of ibus_vi.ia
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getIa() {
        return ia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.ia
     *
     * @param ia the value for ibus_vi.ia
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setIa(Double ia) {
        this.ia = ia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.ib
     *
     * @return the value of ibus_vi.ib
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getIb() {
        return ib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.ib
     *
     * @param ib the value for ibus_vi.ib
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setIb(Double ib) {
        this.ib = ib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.ic
     *
     * @return the value of ibus_vi.ic
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getIc() {
        return ic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.ic
     *
     * @param ic the value for ibus_vi.ic
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setIc(Double ic) {
        this.ic = ic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.ac_time
     *
     * @return the value of ibus_vi.ac_time
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Date getAcTime() {
        return acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.ac_time
     *
     * @param acTime the value for ibus_vi.ac_time
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setAcTime(Date acTime) {
        this.acTime = acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_vi.node_id
     *
     * @return the value of ibus_vi.node_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_vi.node_id
     *
     * @param nodeId the value for ibus_vi.node_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusVi other = (IbusVi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}