package com.hd.ibus.pojo;

import java.io.Serializable;

public class IbusProject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.project_user
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String projectUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.project_address
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String projectAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.project_name
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.project_maker
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String projectMaker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.gateway_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer gatewayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.node_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer nodeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_project.project_name2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String projectName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.id
     *
     * @return the value of ibus_project.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.id
     *
     * @param id the value for ibus_project.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.project_user
     *
     * @return the value of ibus_project.project_user
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getProjectUser() {
        return projectUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.project_user
     *
     * @param projectUser the value for ibus_project.project_user
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setProjectUser(String projectUser) {
        this.projectUser = projectUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.project_address
     *
     * @return the value of ibus_project.project_address
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getProjectAddress() {
        return projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.project_address
     *
     * @param projectAddress the value for ibus_project.project_address
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setProjectAddress(String projectAddress) {
        this.projectAddress = projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.project_name
     *
     * @return the value of ibus_project.project_name
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.project_name
     *
     * @param projectName the value for ibus_project.project_name
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.project_maker
     *
     * @return the value of ibus_project.project_maker
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getProjectMaker() {
        return projectMaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.project_maker
     *
     * @param projectMaker the value for ibus_project.project_maker
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setProjectMaker(String projectMaker) {
        this.projectMaker = projectMaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.gateway_count
     *
     * @return the value of ibus_project.gateway_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getGatewayCount() {
        return gatewayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.gateway_count
     *
     * @param gatewayCount the value for ibus_project.gateway_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setGatewayCount(Integer gatewayCount) {
        this.gatewayCount = gatewayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.node_count
     *
     * @return the value of ibus_project.node_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getNodeCount() {
        return nodeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.node_count
     *
     * @param nodeCount the value for ibus_project.node_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setNodeCount(Integer nodeCount) {
        this.nodeCount = nodeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_project.project_name2
     *
     * @return the value of ibus_project.project_name2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getProjectName2() {
        return projectName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_project.project_name2
     *
     * @param projectName2 the value for ibus_project.project_name2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setProjectName2(String projectName2) {
        this.projectName2 = projectName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusProject other = (IbusProject) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}