package com.hd.ibus.pojo;

import java.io.Serializable;
import java.util.Date;

public class IbusTpvi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp1
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp2
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp3
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp4
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp5
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp6
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp7
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp8
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.tp9
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float tp9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.va
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float va;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.vb
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float vb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.vc
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float vc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.ia
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float ia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.ib
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float ib;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.ic
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Float ic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.gateway_id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Integer gatewayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.node_id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Integer nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tpvi.ac_time
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private Date acTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_tpvi
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.id
     *
     * @return the value of ibus_tpvi.id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.id
     *
     * @param id the value for ibus_tpvi.id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp1
     *
     * @return the value of ibus_tpvi.tp1
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp1() {
        return tp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp1
     *
     * @param tp1 the value for ibus_tpvi.tp1
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp1(Float tp1) {
        this.tp1 = tp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp2
     *
     * @return the value of ibus_tpvi.tp2
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp2() {
        return tp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp2
     *
     * @param tp2 the value for ibus_tpvi.tp2
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp2(Float tp2) {
        this.tp2 = tp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp3
     *
     * @return the value of ibus_tpvi.tp3
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp3() {
        return tp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp3
     *
     * @param tp3 the value for ibus_tpvi.tp3
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp3(Float tp3) {
        this.tp3 = tp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp4
     *
     * @return the value of ibus_tpvi.tp4
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp4() {
        return tp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp4
     *
     * @param tp4 the value for ibus_tpvi.tp4
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp4(Float tp4) {
        this.tp4 = tp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp5
     *
     * @return the value of ibus_tpvi.tp5
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp5() {
        return tp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp5
     *
     * @param tp5 the value for ibus_tpvi.tp5
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp5(Float tp5) {
        this.tp5 = tp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp6
     *
     * @return the value of ibus_tpvi.tp6
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp6() {
        return tp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp6
     *
     * @param tp6 the value for ibus_tpvi.tp6
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp6(Float tp6) {
        this.tp6 = tp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp7
     *
     * @return the value of ibus_tpvi.tp7
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp7() {
        return tp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp7
     *
     * @param tp7 the value for ibus_tpvi.tp7
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp7(Float tp7) {
        this.tp7 = tp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp8
     *
     * @return the value of ibus_tpvi.tp8
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp8() {
        return tp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp8
     *
     * @param tp8 the value for ibus_tpvi.tp8
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp8(Float tp8) {
        this.tp8 = tp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.tp9
     *
     * @return the value of ibus_tpvi.tp9
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getTp9() {
        return tp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.tp9
     *
     * @param tp9 the value for ibus_tpvi.tp9
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setTp9(Float tp9) {
        this.tp9 = tp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.va
     *
     * @return the value of ibus_tpvi.va
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getVa() {
        return va;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.va
     *
     * @param va the value for ibus_tpvi.va
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setVa(Float va) {
        this.va = va;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.vb
     *
     * @return the value of ibus_tpvi.vb
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getVb() {
        return vb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.vb
     *
     * @param vb the value for ibus_tpvi.vb
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setVb(Float vb) {
        this.vb = vb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.vc
     *
     * @return the value of ibus_tpvi.vc
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getVc() {
        return vc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.vc
     *
     * @param vc the value for ibus_tpvi.vc
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setVc(Float vc) {
        this.vc = vc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.ia
     *
     * @return the value of ibus_tpvi.ia
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getIa() {
        return ia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.ia
     *
     * @param ia the value for ibus_tpvi.ia
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setIa(Float ia) {
        this.ia = ia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.ib
     *
     * @return the value of ibus_tpvi.ib
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getIb() {
        return ib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.ib
     *
     * @param ib the value for ibus_tpvi.ib
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setIb(Float ib) {
        this.ib = ib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.ic
     *
     * @return the value of ibus_tpvi.ic
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Float getIc() {
        return ic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.ic
     *
     * @param ic the value for ibus_tpvi.ic
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setIc(Float ic) {
        this.ic = ic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.gateway_id
     *
     * @return the value of ibus_tpvi.gateway_id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Integer getGatewayId() {
        return gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.gateway_id
     *
     * @param gatewayId the value for ibus_tpvi.gateway_id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setGatewayId(Integer gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.node_id
     *
     * @return the value of ibus_tpvi.node_id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.node_id
     *
     * @param nodeId the value for ibus_tpvi.node_id
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tpvi.ac_time
     *
     * @return the value of ibus_tpvi.ac_time
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public Date getAcTime() {
        return acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tpvi.ac_time
     *
     * @param acTime the value for ibus_tpvi.ac_time
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    public void setAcTime(Date acTime) {
        this.acTime = acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tpvi
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusTpvi other = (IbusTpvi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tpvi
     *
     * @mbggenerated Tue Oct 18 13:47:53 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}