package com.hd.ibus.pojo;

import java.io.Serializable;

public class IbusGateway implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.gateway_name
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String gatewayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.gateway_ip
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String gatewayIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.gateway_port
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer gatewayPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.project_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.is_online
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer isOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.group_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer groupCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.node_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer nodeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_gateway.gateway_name2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private String gatewayName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_gateway
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.id
     *
     * @return the value of ibus_gateway.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.id
     *
     * @param id the value for ibus_gateway.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.gateway_name
     *
     * @return the value of ibus_gateway.gateway_name
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getGatewayName() {
        return gatewayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.gateway_name
     *
     * @param gatewayName the value for ibus_gateway.gateway_name
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setGatewayName(String gatewayName) {
        this.gatewayName = gatewayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.gateway_ip
     *
     * @return the value of ibus_gateway.gateway_ip
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getGatewayIp() {
        return gatewayIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.gateway_ip
     *
     * @param gatewayIp the value for ibus_gateway.gateway_ip
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setGatewayIp(String gatewayIp) {
        this.gatewayIp = gatewayIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.gateway_port
     *
     * @return the value of ibus_gateway.gateway_port
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getGatewayPort() {
        return gatewayPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.gateway_port
     *
     * @param gatewayPort the value for ibus_gateway.gateway_port
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setGatewayPort(Integer gatewayPort) {
        this.gatewayPort = gatewayPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.project_id
     *
     * @return the value of ibus_gateway.project_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.project_id
     *
     * @param projectId the value for ibus_gateway.project_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.is_online
     *
     * @return the value of ibus_gateway.is_online
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getIsOnline() {
        return isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.is_online
     *
     * @param isOnline the value for ibus_gateway.is_online
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setIsOnline(Integer isOnline) {
        this.isOnline = isOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.group_count
     *
     * @return the value of ibus_gateway.group_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getGroupCount() {
        return groupCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.group_count
     *
     * @param groupCount the value for ibus_gateway.group_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setGroupCount(Integer groupCount) {
        this.groupCount = groupCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.node_count
     *
     * @return the value of ibus_gateway.node_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getNodeCount() {
        return nodeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.node_count
     *
     * @param nodeCount the value for ibus_gateway.node_count
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setNodeCount(Integer nodeCount) {
        this.nodeCount = nodeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_gateway.gateway_name2
     *
     * @return the value of ibus_gateway.gateway_name2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public String getGatewayName2() {
        return gatewayName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_gateway.gateway_name2
     *
     * @param gatewayName2 the value for ibus_gateway.gateway_name2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setGatewayName2(String gatewayName2) {
        this.gatewayName2 = gatewayName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_gateway
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusGateway other = (IbusGateway) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_gateway
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}