package com.hd.ibus.pojo;

import java.io.Serializable;
import java.util.Date;

public class IbusTp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp1
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp3
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp4
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp5
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp6
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp7
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp8
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.tp9
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Double tp9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.node_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Integer nodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_tp.ac_time
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private Date acTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.id
     *
     * @return the value of ibus_tp.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.id
     *
     * @param id the value for ibus_tp.id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp1
     *
     * @return the value of ibus_tp.tp1
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp1() {
        return tp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp1
     *
     * @param tp1 the value for ibus_tp.tp1
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp1(Double tp1) {
        this.tp1 = tp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp2
     *
     * @return the value of ibus_tp.tp2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp2() {
        return tp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp2
     *
     * @param tp2 the value for ibus_tp.tp2
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp2(Double tp2) {
        this.tp2 = tp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp3
     *
     * @return the value of ibus_tp.tp3
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp3() {
        return tp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp3
     *
     * @param tp3 the value for ibus_tp.tp3
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp3(Double tp3) {
        this.tp3 = tp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp4
     *
     * @return the value of ibus_tp.tp4
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp4() {
        return tp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp4
     *
     * @param tp4 the value for ibus_tp.tp4
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp4(Double tp4) {
        this.tp4 = tp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp5
     *
     * @return the value of ibus_tp.tp5
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp5() {
        return tp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp5
     *
     * @param tp5 the value for ibus_tp.tp5
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp5(Double tp5) {
        this.tp5 = tp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp6
     *
     * @return the value of ibus_tp.tp6
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp6() {
        return tp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp6
     *
     * @param tp6 the value for ibus_tp.tp6
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp6(Double tp6) {
        this.tp6 = tp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp7
     *
     * @return the value of ibus_tp.tp7
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp7() {
        return tp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp7
     *
     * @param tp7 the value for ibus_tp.tp7
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp7(Double tp7) {
        this.tp7 = tp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp8
     *
     * @return the value of ibus_tp.tp8
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp8() {
        return tp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp8
     *
     * @param tp8 the value for ibus_tp.tp8
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp8(Double tp8) {
        this.tp8 = tp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.tp9
     *
     * @return the value of ibus_tp.tp9
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Double getTp9() {
        return tp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.tp9
     *
     * @param tp9 the value for ibus_tp.tp9
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setTp9(Double tp9) {
        this.tp9 = tp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.node_id
     *
     * @return the value of ibus_tp.node_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.node_id
     *
     * @param nodeId the value for ibus_tp.node_id
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_tp.ac_time
     *
     * @return the value of ibus_tp.ac_time
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public Date getAcTime() {
        return acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_tp.ac_time
     *
     * @param acTime the value for ibus_tp.ac_time
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    public void setAcTime(Date acTime) {
        this.acTime = acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusTp other = (IbusTp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}