package com.hd.ibus.pojo;

import java.io.Serializable;
import java.util.Date;

public class IbusOperation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_operation.id
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_operation.user_id
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_operation.operation_type
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_operation.operation_name
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    private String operationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_operation.ac_time
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    private Date acTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_operation.id
     *
     * @return the value of ibus_operation.id
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_operation.id
     *
     * @param id the value for ibus_operation.id
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_operation.user_id
     *
     * @return the value of ibus_operation.user_id
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_operation.user_id
     *
     * @param userId the value for ibus_operation.user_id
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_operation.operation_type
     *
     * @return the value of ibus_operation.operation_type
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_operation.operation_type
     *
     * @param operationType the value for ibus_operation.operation_type
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_operation.operation_name
     *
     * @return the value of ibus_operation.operation_name
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_operation.operation_name
     *
     * @param operationName the value for ibus_operation.operation_name
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public void setOperationName(String operationName) {
        this.operationName = operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_operation.ac_time
     *
     * @return the value of ibus_operation.ac_time
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public Date getAcTime() {
        return acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_operation.ac_time
     *
     * @param acTime the value for ibus_operation.ac_time
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    public void setAcTime(Date acTime) {
        this.acTime = acTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusOperation other = (IbusOperation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}