package com.hd.ibus.pojo;

import java.io.Serializable;

public class IbusExist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_exist.id
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_exist.gateway_id
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    private Integer gatewayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_exist.table_name
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_exist
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_exist.id
     *
     * @return the value of ibus_exist.id
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_exist.id
     *
     * @param id the value for ibus_exist.id
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_exist.gateway_id
     *
     * @return the value of ibus_exist.gateway_id
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    public Integer getGatewayId() {
        return gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_exist.gateway_id
     *
     * @param gatewayId the value for ibus_exist.gateway_id
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    public void setGatewayId(Integer gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_exist.table_name
     *
     * @return the value of ibus_exist.table_name
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_exist.table_name
     *
     * @param tableName the value for ibus_exist.table_name
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_exist
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusExist other = (IbusExist) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_exist
     *
     * @mbggenerated Tue Nov 01 14:35:32 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}