package com.hd.ibus.pojo;

import java.io.Serializable;

public class IbusNode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.node_name
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.node_address
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer nodeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.node_type
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer nodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.node_type2
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer nodeType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.node_state
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer nodeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.y
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.x
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.v_mix
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Float vMix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.v_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Float vMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.i_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Float iMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.tp_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Float tpMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.group_id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.gateway_id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer gatewayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.node_isonline
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private Integer nodeIsonline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_node.node_name2
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private String nodeName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.id
     *
     * @return the value of ibus_node.id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.id
     *
     * @param id the value for ibus_node.id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.node_name
     *
     * @return the value of ibus_node.node_name
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.node_name
     *
     * @param nodeName the value for ibus_node.node_name
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.node_address
     *
     * @return the value of ibus_node.node_address
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getNodeAddress() {
        return nodeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.node_address
     *
     * @param nodeAddress the value for ibus_node.node_address
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setNodeAddress(Integer nodeAddress) {
        this.nodeAddress = nodeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.node_type
     *
     * @return the value of ibus_node.node_type
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.node_type
     *
     * @param nodeType the value for ibus_node.node_type
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.node_type2
     *
     * @return the value of ibus_node.node_type2
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getNodeType2() {
        return nodeType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.node_type2
     *
     * @param nodeType2 the value for ibus_node.node_type2
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setNodeType2(Integer nodeType2) {
        this.nodeType2 = nodeType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.node_state
     *
     * @return the value of ibus_node.node_state
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getNodeState() {
        return nodeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.node_state
     *
     * @param nodeState the value for ibus_node.node_state
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setNodeState(Integer nodeState) {
        this.nodeState = nodeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.y
     *
     * @return the value of ibus_node.y
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.y
     *
     * @param y the value for ibus_node.y
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.x
     *
     * @return the value of ibus_node.x
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.x
     *
     * @param x the value for ibus_node.x
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.v_mix
     *
     * @return the value of ibus_node.v_mix
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Float getvMix() {
        return vMix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.v_mix
     *
     * @param vMix the value for ibus_node.v_mix
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setvMix(Float vMix) {
        this.vMix = vMix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.v_max
     *
     * @return the value of ibus_node.v_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Float getvMax() {
        return vMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.v_max
     *
     * @param vMax the value for ibus_node.v_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setvMax(Float vMax) {
        this.vMax = vMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.i_max
     *
     * @return the value of ibus_node.i_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Float getiMax() {
        return iMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.i_max
     *
     * @param iMax the value for ibus_node.i_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setiMax(Float iMax) {
        this.iMax = iMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.tp_max
     *
     * @return the value of ibus_node.tp_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Float getTpMax() {
        return tpMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.tp_max
     *
     * @param tpMax the value for ibus_node.tp_max
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setTpMax(Float tpMax) {
        this.tpMax = tpMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.group_id
     *
     * @return the value of ibus_node.group_id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.group_id
     *
     * @param groupId the value for ibus_node.group_id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.gateway_id
     *
     * @return the value of ibus_node.gateway_id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getGatewayId() {
        return gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.gateway_id
     *
     * @param gatewayId the value for ibus_node.gateway_id
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setGatewayId(Integer gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.node_isonline
     *
     * @return the value of ibus_node.node_isonline
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public Integer getNodeIsonline() {
        return nodeIsonline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.node_isonline
     *
     * @param nodeIsonline the value for ibus_node.node_isonline
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setNodeIsonline(Integer nodeIsonline) {
        this.nodeIsonline = nodeIsonline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_node.node_name2
     *
     * @return the value of ibus_node.node_name2
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public String getNodeName2() {
        return nodeName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_node.node_name2
     *
     * @param nodeName2 the value for ibus_node.node_name2
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    public void setNodeName2(String nodeName2) {
        this.nodeName2 = nodeName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusNode other = (IbusNode) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}