package com.hd.ibus.pojo;

import java.io.Serializable;

public class IbusGroup implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.id
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.group_name
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.gateway_id
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private Integer gatewayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.group_state
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private Integer groupState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.node_count
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private Integer nodeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.file_url
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.file_name
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ibus_group.group_name2
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private String groupName2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.id
     *
     * @return the value of ibus_group.id
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.id
     *
     * @param id the value for ibus_group.id
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.group_name
     *
     * @return the value of ibus_group.group_name
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.group_name
     *
     * @param groupName the value for ibus_group.group_name
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.gateway_id
     *
     * @return the value of ibus_group.gateway_id
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public Integer getGatewayId() {
        return gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.gateway_id
     *
     * @param gatewayId the value for ibus_group.gateway_id
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setGatewayId(Integer gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.group_state
     *
     * @return the value of ibus_group.group_state
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public Integer getGroupState() {
        return groupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.group_state
     *
     * @param groupState the value for ibus_group.group_state
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setGroupState(Integer groupState) {
        this.groupState = groupState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.node_count
     *
     * @return the value of ibus_group.node_count
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public Integer getNodeCount() {
        return nodeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.node_count
     *
     * @param nodeCount the value for ibus_group.node_count
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setNodeCount(Integer nodeCount) {
        this.nodeCount = nodeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.file_url
     *
     * @return the value of ibus_group.file_url
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.file_url
     *
     * @param fileUrl the value for ibus_group.file_url
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.file_name
     *
     * @return the value of ibus_group.file_name
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.file_name
     *
     * @param fileName the value for ibus_group.file_name
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ibus_group.group_name2
     *
     * @return the value of ibus_group.group_name2
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public String getGroupName2() {
        return groupName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ibus_group.group_name2
     *
     * @param groupName2 the value for ibus_group.group_name2
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    public void setGroupName2(String groupName2) {
        this.groupName2 = groupName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IbusGroup other = (IbusGroup) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}