package com.hd.ibus.mapper;

import com.hd.ibus.pojo.IbusNode;

public interface IbusNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    int insert(IbusNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    int insertSelective(IbusNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    IbusNode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    int updateByPrimaryKeySelective(IbusNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_node
     *
     * @mbggenerated Thu Oct 20 17:08:04 CST 2016
     */
    int updateByPrimaryKey(IbusNode record);
}