package com.hd.ibus.mapper;

import com.hd.ibus.pojo.IbusOperation;

public interface IbusOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int insert(IbusOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int insertSelective(IbusOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    IbusOperation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int updateByPrimaryKeySelective(IbusOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int updateByPrimaryKey(IbusOperation record);
}