package com.hd.ibus.mapper;

import com.hd.ibus.pojo.IbusGroup;

public interface IbusGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    int insert(IbusGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    int insertSelective(IbusGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    IbusGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    int updateByPrimaryKeySelective(IbusGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_group
     *
     * @mbggenerated Fri Oct 21 15:23:17 CST 2016
     */
    int updateByPrimaryKey(IbusGroup record);
}