package com.hd.ibus.mapper;

import com.hd.ibus.pojo.IbusWarn;

public interface IbusWarnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_warn
     *
     * @mbggenerated Wed Oct 19 18:51:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_warn
     *
     * @mbggenerated Wed Oct 19 18:51:58 CST 2016
     */
    int insert(IbusWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_warn
     *
     * @mbggenerated Wed Oct 19 18:51:58 CST 2016
     */
    int insertSelective(IbusWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_warn
     *
     * @mbggenerated Wed Oct 19 18:51:58 CST 2016
     */
    IbusWarn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_warn
     *
     * @mbggenerated Wed Oct 19 18:51:58 CST 2016
     */
    int updateByPrimaryKeySelective(IbusWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_warn
     *
     * @mbggenerated Wed Oct 19 18:51:58 CST 2016
     */
    int updateByPrimaryKey(IbusWarn record);
}