package com.hd.ibus.mapper;

import com.hd.ibus.pojo.IbusVi;

public interface IbusViMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int insert(IbusVi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int insertSelective(IbusVi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    IbusVi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int updateByPrimaryKeySelective(IbusVi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_vi
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int updateByPrimaryKey(IbusVi record);
}