package com.hd.ibus.mapper;

import com.hd.ibus.pojo.Operation;

public interface IbusOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int insertSelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    Operation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int updateByPrimaryKeySelective(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_operation
     *
     * @mbggenerated Wed Nov 09 17:04:05 CST 2016
     */
    int updateByPrimaryKey(Operation record);
}