package com.hd.ibus.mapper;

import com.hd.ibus.pojo.IbusTp;

public interface IbusTpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int insert(IbusTp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int insertSelective(IbusTp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    IbusTp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int updateByPrimaryKeySelective(IbusTp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_tp
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int updateByPrimaryKey(IbusTp record);
}