package com.hd.ibus.mapper;

import com.hd.ibus.pojo.IbusProject;

public interface IbusProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int insert(IbusProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int insertSelective(IbusProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    IbusProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int updateByPrimaryKeySelective(IbusProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ibus_project
     *
     * @mbggenerated Tue Oct 11 16:37:18 CST 2016
     */
    int updateByPrimaryKey(IbusProject record);
}